# Generated by Django 5.2.4 on 2025-07-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='pais',
            field=models.CharField(default='Argentina', max_length=100),
        ),
        migrations.AddField(
            model_name='torneo',
            name='fecha_fin',
            field=models.DateField(default='2025-12-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='torneo',
            name='pais',
            field=models.CharField(default='Argentina', max_length=100),
        ),
    ]
