# Generated by Django 5.2.4 on 2025-07-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_torneo_partido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='edad',
        ),
        migrations.AddField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(default='Desconocido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='ranking',
            field=models.IntegerField(),
        ),
    ]
