# Generated by Django 5.2.4 on 2025-07-23 15:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_jugador_pais_torneo_fecha_fin_torneo_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_ganados', to='gestion.jugador'),
        ),
        migrations.AddField(
            model_name='partido',
            name='jugador3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_jugador3', to='gestion.jugador'),
        ),
        migrations.AddField(
            model_name='partido',
            name='jugador4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_jugador4', to='gestion.jugador'),
        ),
        migrations.AddField(
            model_name='partido',
            name='modalidad',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('DOBLES', 'Dobles')], default='SINGLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='partido',
            name='resultado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2025, 12, 31)),
        ),
    ]
